MvcProjeKampi/Controllers/WriterPanelContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
	public class WriterPanelContentController : Controller
	{
		// GET: WriterPanelContent
		ContentManager cm = new ContentManager(new EfContentDal());
		Context c = new Context();

		public ActionResult MyContent(string p)
		{
			Context c = new Context();
			p = (string)Session["WriterMail"];
			var writeridinfo = c.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault();
			var contentvalues = cm.GetListByWriter(writeridinfo);
			return View(contentvalues);
		}
		[HttpGet]
		public ActionResult AddContent(int id)
		{
			ViewBag.d = id;
			return View();
		}
		[HttpPost]
		public ActionResult AddContent(Content p)
		{
			string mail = (string)Session["WriterMail"];
			var writeridinfo = c.Writers.Where(x => x.WriterMail == mail).Select(y => y.WriterID).FirstOrDefault();
			p.ContentDate = DateTime.Parse(DateTime.Now.ToShortDateString());
			p.WriterID = writeridinfo;
			p.ContentStatus = true;
			cm.ContentAdd(p);
			return RedirectToAction("MyContent");
		}
	}
}

MvcProjeKampi/Views/WriterPanelContent/AddContent.cshtml
@model EntityLayer.Concrete.Content

@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>İçerik Girişi</h2>
<br />
@using (Html.BeginForm("AddContent", "WriterPanelContent", FormMethod.Post))
{
    <div class="form-group">
        <input type="hidden" name="HeadingID" value="@ViewBag.d" />
        @Html.Label("İçeriğinizi Yazın")
        @Html.TextAreaFor(x => x.ContentValue, 10, 30, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ContentValue)
        <br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}

MvcProjeKampi/Views/WriterPanelContent/MyContent.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "MyContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}
<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="timeline">
                            @foreach (var item in Model)
                            {
                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd-MMM-yyyy"))</span>
                                </div>
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Heading.HeadingName</a></h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</body>
</html>